steps:
  # Step 1: Check if input files have changed since last graph build
  # Pass _FORCE_BUILD=true to skip this check (e.g. after OTP source changes)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_FORCE_BUILD}" = "true" ]; then
          echo "Forced build requested — skipping hash check"
          echo "forced" > /workspace/current-hash.txt
          exit 0
        fi

        CURRENT_HASH=$$(gsutil stat \
          gs://skilift-otp-data/kcm-gtfs.zip \
          gs://skilift-otp-data/st-gtfs.zip \
          gs://skilift-otp-data/seattle.osm.pbf \
          gs://skilift-otp-data/seattle-dem.tif \
          gs://skilift-otp-data/build-config.json \
          gs://skilift-otp-data/otp-config.json \
          gs://skilift-otp-data/router-config.json \
          | grep 'Hash (crc32c)' | awk '{print $$NF}' | tr -d '\n')

        STORED_HASH=$$(gsutil cat gs://skilift-otp-data/graph-input-hash.txt 2>/dev/null || echo '')

        echo "Current input hash: $$CURRENT_HASH"
        echo "Stored input hash:  $$STORED_HASH"

        if [ "$$CURRENT_HASH" = "$$STORED_HASH" ]; then
          echo "Input files unchanged — skipping graph build"
          touch /workspace/skip-build
        else
          echo "Input files changed — graph build needed"
          echo "$$CURRENT_HASH" > /workspace/current-hash.txt
        fi

  # Step 2: Download source data, config, and elevation cache from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f /workspace/skip-build ]; then
          echo "Skipping download — inputs unchanged"
          exit 0
        fi
        gsutil -m cp \
          gs://skilift-otp-data/kcm-gtfs.zip \
          gs://skilift-otp-data/st-gtfs.zip \
          gs://skilift-otp-data/seattle.osm.pbf \
          gs://skilift-otp-data/seattle-dem.tif \
          gs://skilift-otp-data/build-config.json \
          gs://skilift-otp-data/otp-config.json \
          gs://skilift-otp-data/router-config.json \
          /otp-data/
        mkdir -p /otp-cache
        gsutil cp gs://skilift-otp-data/cached_elevations.obj /otp-cache/ 2>/dev/null \
          && echo "Loaded elevation cache from GCS" \
          || echo "No elevation cache found — will compute from scratch"
    volumes:
      - name: 'otp-data'
        path: '/otp-data'
      - name: 'otp-cache'
        path: '/otp-cache'

  # Step 3: Build the OTP graph (skipped if inputs unchanged)
  - name: 'us-west1-docker.pkg.dev/skilift-450102/otp/opentripplanner:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f /workspace/skip-build ]; then
          echo "Skipping graph build — inputs unchanged"
          exit 0
        fi
        exec /docker-entrypoint.sh --build --save --cache /var/otp/cache /var/opentripplanner
    env:
      - 'JAVA_OPTS=-Xmx12g'
    volumes:
      - name: 'otp-data'
        path: '/var/opentripplanner'
      - name: 'otp-cache'
        path: '/var/otp/cache'

  # Step 4: Upload the built graph, elevation cache, and updated hash to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f /workspace/skip-build ]; then
          echo "Skipping upload — inputs unchanged"
          exit 0
        fi
        gsutil cp /otp-data/graph.obj gs://skilift-otp-data/
        gsutil cp /workspace/current-hash.txt gs://skilift-otp-data/graph-input-hash.txt
        if [ -f /otp-cache/cached_elevations.obj ]; then
          echo "Uploading elevation cache..."
          gsutil cp /otp-cache/cached_elevations.obj gs://skilift-otp-data/
        fi
    volumes:
      - name: 'otp-data'
        path: '/otp-data'
      - name: 'otp-cache'
        path: '/otp-cache'

substitutions:
  _FORCE_BUILD: 'false'

timeout: '3600s'
options:
  machineType: 'E2_HIGHCPU_32'
