steps:
  # Step 1: Download the pre-built graph and config from GCS to the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='mkdir -p $$HOME/skilift/otp/data && gsutil -m cp gs://skilift-otp-data/graph.obj gs://skilift-otp-data/otp-config.json gs://skilift-otp-data/router-config.json $$HOME/skilift/otp/data/'

  # Step 2: Configure Docker on the VM to pull from Artifact Registry, then pull the image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo gcloud auth configure-docker us-west1-docker.pkg.dev --quiet && sudo docker pull us-west1-docker.pkg.dev/skilift-450102/otp/opentripplanner:latest'

  # Step 3: Stop and remove the old OTP server container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo docker stop otp-server 2>/dev/null; sudo docker rm otp-server 2>/dev/null; true'

  # Step 4: Start the new OTP server
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo docker run -d --name otp-server --restart=always -v $$HOME/skilift/otp/data:/var/opentripplanner -p 8080:8080 -e JAVA_OPTS="-Xmx8g" us-west1-docker.pkg.dev/skilift-450102/otp/opentripplanner:latest --load --serve /var/opentripplanner'

timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY
