steps:
  # Step 1: Upload runtime config files from repo to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - 'otp/otp-config.json'
      - 'otp/router-config.json'
      - 'gs://skilift-otp-data/'

  # Step 2: Download the pre-built graph from GCS and copy configs from repo to the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='mkdir -p $$HOME/skilift/otp/data && gsutil cp gs://skilift-otp-data/graph.obj $$HOME/skilift/otp/data/'
        gcloud compute scp \
          otp/otp-config.json otp/router-config.json \
          skilift-otp:~/skilift/otp/data/ \
          --zone=us-west1-b

  # Step 3: Configure Docker on the VM to pull from Artifact Registry, then pull the image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo gcloud auth configure-docker us-west1-docker.pkg.dev --quiet && sudo docker pull us-west1-docker.pkg.dev/skilift-450102/otp/opentripplanner:latest'

  # Step 4: Stop and remove the old OTP server container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo docker stop otp-server 2>/dev/null; sudo docker rm otp-server 2>/dev/null; true'

  # Step 5: Start the new OTP server
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh skilift-otp \
          --zone=us-west1-b \
          --command='sudo docker run -d --name otp-server --restart=always -v $$HOME/skilift/otp/data:/var/opentripplanner -p 8080:8080 -e JAVA_OPTS="-Xmx8g" us-west1-docker.pkg.dev/skilift-450102/otp/opentripplanner:latest --load --serve /var/opentripplanner'

timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY
